version: '3.1'
services:
  log-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
  log-kibana:
    image: docker.elastic.co/kibana/kibana:5.6.2
    environment:
      - xpack.security.enabled=false
      - "ELASTICSEARCH_URL=http://log-elasticsearch:9200"

    ports:
      - 5601:5601
  log-fluentd-bit:
    build: logging/fluentd
    ports:
      - "24224:24224"
      - "24224:24224/udp"
volumes:
  logger: